config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "ideas#index"

  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create]

  resources :ideas do
    resources :reviews, shallow: true, only: [:create, :destroy]
    resources :likes, shallow: true, only: [:create, :destroy]

  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    can(:update, Idea) do |idea|
      idea.user == user
    end

    can(:destroy, Idea) do |idea|
      idea.user == user
    end

    can(:destroy, Review) do |review|
      review.user == user
    end

    can(:like, Idea) do |idea|
      user.present? && idea.user != user
    end

    can(:destroy, Like) do |like|
      like.user == user
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/idea.rb
class Idea < ApplicationRecord
  has_many :reviews, dependent: :destroy
  has_many :likes, dependent: :destroy

  belongs_to :user

  validates :title, {
    presence: true
  }
validates :description, {
    presence: true,
    length: { minimum: 10 },
  }
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :idea

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :idea

  validates :body, {
    presence: true
  }
end

app/models/user.rb
class User < ApplicationRecord
    has_many :ideas, dependent: :destroy
    has_many :reviews, dependent: :destroy
    has_many :likes, dependent: :destroy


    has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  private

  def user_signed_in?
    current_user.present?
  end

  helper_method :user_signed_in?

  def current_user
    if session[:user_id].present?
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  helper_method :current_user

  def authenticated_user!
    unless user_signed_in?
      flash[:alert] = "You must sign in or sign up first"
      redirect_to ideas_path
    end
  end

  def password_correct?(password)
    current_user&.authenticate(password)
  end

  helper_method :password_correct?
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :authenticated_user!, except: [:index, :show]

  before_action :find_idea, only: [:show, :edit, :update, :destroy]
  before_action :authorize!, only: [:edit, :update]

  def index
    @ideas = Idea.all.order(updated_at: :desc)
    @likes = Like.where(user: current_user)
  end

  def new
    @idea = Idea.new
  end

  def show
    @review = Review.new
    @reviews = @idea.reviews.order(updated_at: :desc)
  end

  def create
    @idea = Idea.new idea_params
    @idea.user = @current_user
    if @idea.save
      redirect_to @idea
    else
      render :new
    end
  end

  def update
    if !can?(:update, @idea)
      flash[:warning] = "You can't update a idea you don't own"
      redirect_to ideas_path
    else
      if @idea.update idea_params
        redirect_to idea_path(@idea)
      else
        render :edit
      end
    end
  end

  def destroy
    if !can?(:destroy, @idea)
      flash[:warning] = "You can't delete a idea you don't own"
      redirect_to ideas_path
    else
      @idea.destroy
      redirect_to ideas_path
    end
  end

  private

  def idea_params
    params.require(:idea).permit(:title, :description)
  end

  def find_idea
    @idea = Idea.find params[:id]
  end

  def authorize!
    redirect_to ideas_path, alert: "access denied" unless can? :update, @idea
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticated_user!, only: [:create, :destroy]

  def create
    idea = Idea.find params[:idea_id]
    like = Like.new(idea: idea, user: current_user)

    if !can?(:like, idea)
      flash[:alert] = "You can't like your own Idea"
    elsif like.save
      flash[:success] = "Idea Liked"
    else
      flash[:alert] = like.errors.full_messages.join(", ")
    end
    redirect_to ideas_path
  end

  def destroy
# byebug
    like = current_user.likes.find params[:id]

    if !can?(:destroy, like)
      flash[:warning] = "you can't destroy a like you don't own"
    elsif like.destroy
      flash[:success] = "Idea Unliked"
    else
      flash[:warning] = "It's rude to unlike something you've already liked"
    end

    redirect_to ideas_path
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    before_action :authenticated_user!, except: [:index, :show]
  
    # before_action :authorize!, only: [:edit, :update, :destroy]
    
    def create
      @idea = Idea.find(params[:idea_id])
      @review = Review.new review_params
      @review.user = @current_user
      @review.idea = @idea
      if @review.save
        redirect_to @idea
      else
        @reviews = @idea.reviews.order(created_at: :desc)
        render "ideas/show"
      end
    end
  
    def destroy
      @review = Review.find params[:id]
      @review.destroy
      redirect_to @review.idea
    end
  
    private
  
    def review_params
      params.require(:review).permit(:body)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end
  
    def create
      user = User.find_by(email: session_params[:email])
      if user&.authenticate(session_params[:password])
        session[:user_id] = user.id
        flash[:notice] = "Thank you for Signing in!"
        redirect_to ideas_path
      else
        flash.now[:alert] = "Wrong email or password"
        render :new
      end
    end
  
    def destroy
      session[:user_id] = nil
      flash[:notice] = "Signed out!"
      redirect_to ideas_path
    end
  
    private
  
    def session_params
      params.require(:session).permit(:email, :password)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Thank you for Signing in!"
      redirect_to ideas_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/ideas/_form.html.erb
<div class="post-form">

    <% if @idea.errors.any? %>
    <ul>
        <% @idea.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
    </ul>
    <% end %>

    <%= form_for @idea do |f| %>
    <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control' %>
    </div>
    <div class="form-group">
        <%= f.label :description %>
        <%= f.text_field :description, class: 'form-control' %>
    </div>
    <%= f.submit 'Submit', class: 'btn btn-success'%>
    <% end %>
</div>

app/views/ideas/edit.html.erb
<h1>Update Idea</h1>
<%= render 'form' %>

app/views/ideas/index.html.erb
<div class="ideas">
    <% @ideas.each do |idea| %>
    <div class="idea">
        <div class="ideatitle">
            <%= link_to( idea.title, idea_path(idea) )%>
        </div>
        <div class="ideadescription"><%= idea.description %></div>
        <div class="ideafooter">
            <div class="footerLeft">
                <div class="ideaauthor">by <%= idea.user.name %></div>
                <div class="idealikes">
                    <% @like = @likes.where(idea: idea).first %>
                    <% if @like.present? %>
                        <%= link_to( "Unlike", like_path(@like), method: :delete )%>
                    <% else %>
                        <%= link_to( "Like", idea_likes_path(idea), method: :post )%>
                    <% end %>
                </div>
            </div>
            <div class="footerRight">
                <div class="reviewsCount">Reviews: <%= idea.reviews.count %></div>
                <div class="between">|</div>
                <div class="likesCount">Likes: <%= idea.likes.count %></div>
            </div>
        </div>
    </div>

    <% end %>
</div>

app/views/ideas/new.html.erb
<h1>New Idea</h1>
<%= render 'form' %>

app/views/ideas/show.html.erb
<div class="card" style="border: none">
  <div class="card-body">
    <h1 class="card-title"><%= @idea.title %></h1>
    <p class="card-text"><%= @idea.description %></p>
    <p><small style="color:silver;">Updated by <b><%= @idea.user&.name %></b></small></p>
    <% if can? :update, @idea %>
    <%= link_to "Edit", edit_idea_path(@idea), class: "btn btn-outline-primary" %>
    <% end %>
    <% if can? :destroy, @idea %>
    <%= link_to 'Delete', 
          idea_path(@idea), 
          class: "btn btn-outline-primary",
          method: :delete, 
          data: { confirm: 'Are you sure that you want to delete this idea? '} 
      %>
    <% end %>

  </div>
</div>
<div class="review">
  <h3>Review</h3>

  <%= form_with(model: [@idea, @review], local: true) do |c| %>
  <% if @review.errors.full_messages.each do |msg| %>
  <ul>
    <li class="text-dnger"><%= msg %></li>
  </ul>
  <% end %>
  <% end %>
  <div class="form-group">
    <%= c.text_area(
  :body,
  cols:50,
  rows:5,
  placeholder: "What's on your mind?",
   class: "form-control" 
  )%>
    <%= c.submit "Submit", class: "btn-primary", style:"margin-top:10px;" %>
  </div>
  <% end %>

  <% @reviews.each do |review| %>
  <ul class="list-group">
    <li class="list-group-item" style="border: none; margin-bottom: 0px; padding-bottom: 0px; padding-top: 0;">
      <p style="margin-bottom: 0;"><%= review.body %></p>
      <p style="margin-bottom: 10px;">
        <small style="color:silver; border-bottom: silver dotted 1px;">
          by <%= review.user&.name %>
          <%= distance_of_time_in_words_to_now(review.updated_at)%> ago
        </small>
          <% if can? :destroy, review %>
        <small>
          *
          <%= link_to 'Delete',
                review_path(review),
                method: :delete,
                data: {
                    confirm: 'Are you sure that you want to delete this review?'
                }%>
          <% end %>
        </small>
      </p>
    </li>
  </ul>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PostDiscussIdeas</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>
<header>
  <%= render 'shared/nav' %>
  <%= render 'shared/flash' %>

</header>
  <body>
  </body>
</html>

app/views/shared/_flash.html.erb
<div class="container-fluid">
  <% if flash[:notice].present?%>
  <div class="flash-message flash-notice">
    <%= flash[:notice]%>
  </div>
  <% end %>
  <% if flash[:warning].present?%>
  <div class="flash-message flash-warning">
    <%= flash[:warning]%>
  </div>
  <% end %>
  <% if flash[:alert].present?%>
  <div class="flash-message flash-alert">
    <%= flash[:alert]%>
  </div>
  <% end %>
  <%= yield %>
</div>

app/views/shared/_nav.html.erb
<nav class="navbar">
    <div class="linksNav">
        <div class="left">
            <div class="logo">
                <a href="<%= root_path %>" </a>
                    <div>
                        <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Noun_project_566.svg/860px-Noun_project_566.svg.png"
                            width="30" class="d-inline-block align-top" alt="">
                    </div>
                    <div>
                        Idea Factory
                    </div>
                </a>
            </div>
        </div>
        <div class="right">
            <div class="signNav">
                <% if user_signed_in? %>
                <div class="userName">
                    <%= current_user.name %>
                    <%# link_to current_user.name, edit_user_path(current_user), class: '' %>
                </div>
                <div>
                    <%= link_to 'Logout', session_path, method: :delete, class: 'btn btn-outline-success' %>
                </div>
                <% else %>
                <div>
                    <%= link_to 'Sign In', new_session_path, class: 'btn btn-outline-success' %>
                </div>
                <div>
                    <%= link_to 'Sign Up', new_user_path, class: 'btn btn-outline-success' %>
                </div>
                <% end %>
            </div>
            <div class="newIdea">
                <%= link_to 'New Idea', new_idea_path, class:'btn btn-outline-primary' %>
            </div>
        </div>
    </div>
</nav>

app/views/users/new.html.erb
<div class="user-form">
    <% if @user.errors.any? %>
    <ul>
        <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
    </ul>
    <% end %>

    <%= form_for @user do |f| %>

    <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name , class: 'form-control' %>
    </div>
    <div class="form-group">
        <%= f.label :email %>
        <%= f.email_field :email , class: 'form-control' %>
    </div>
    <div class="form-group">
        <%= f.label :password %>
        <%= f.password_field :password , class: 'form-control' %>
    </div>
    <div class="form-group">
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
    </div>

    <%= f.submit "Sign Up", class: 'btn btn-primary' %>
    <% end %>
</div>